export enum ECommands {
  Backup = "backup",
  Cambiar = "cambiar",
  Help = "help",
  ListarMods = "listar_mods",
  Ping = "ping",
  Reload = "reload",
  Server = "server",
  Servercito = "servercito",
  Start = "start",
  Status = "status",
  Stop = "stop",
  SubirMod = "subir_mod",
  User = "user",
}
